#!/bin/zsh
# Xcode Cloud post-clone hook. Xcode Cloud auto-runs this immediately after
# cloning the repo, before xcodebuild starts.
#
# Regenerates Secrets.xcconfig from the SUPABASE_URL / SUPABASE_ANON_KEY
# environment variables defined in the Xcode Cloud workflow:
#   App Store Connect -> your app -> Xcode Cloud -> workflow -> Environment.
# The real Secrets.xcconfig is gitignored, so it isn't present on the CI clone.

set -euo pipefail

if [[ -z "${SUPABASE_URL:-}" || -z "${SUPABASE_ANON_KEY:-}" ]]; then
    echo "error: SUPABASE_URL or SUPABASE_ANON_KEY missing from Xcode Cloud environment." >&2
    echo "  Add them under App Store Connect -> Xcode Cloud -> workflow -> Environment Variables." >&2
    exit 1
fi

# xcconfig treats // as a line comment, so a raw https:// URL gets truncated
# to https:. $() evaluates to empty at parse time but breaks up the //, which
# survives the parser.
ESCAPED_URL=$(printf '%s' "$SUPABASE_URL" | sed 's|://|:$()/$()/|')

# Xcode Cloud sets CI_WORKSPACE to the repo root (/Volumes/workspace/repository).
# Fall back to the script's parent dir for local runs.
SECRETS_PATH="${CI_WORKSPACE:-$(cd "$(dirname "$0")/.." && pwd)}/Secrets.xcconfig"

cat >"$SECRETS_PATH" <<EOF
// Generated by ci_scripts/ci_post_clone.sh on Xcode Cloud. Do not edit.

SUPABASE_URL = $ESCAPED_URL
SUPABASE_ANON_KEY = $SUPABASE_ANON_KEY
EOF

echo "ci_post_clone: wrote $SECRETS_PATH"
